packages:
  - packages/*

minimumReleaseAge: 0

overrides:
  zod: 4.4.3

allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': true
  '@google/genai': false
  koffi: false
  node-pty: false
  protobufjs: false

catalog:
  '@deepseek-ai/cordis': 4.0.2
  '@deepseek-ai/dsh': 0.1.2-rc.1
  '@deepseek-ai/dsh-agent': 0.1.2-rc.1
  '@deepseek-ai/dsh-agent-loop': 0.1.2-rc.1
  '@deepseek-ai/dsh-agent-loop-testkit': 0.1.2-rc.1
  '@deepseek-ai/dsh-commands': 0.1.2-rc.1
  '@deepseek-ai/dsh-fs': 0.1.2-rc.1
  '@deepseek-ai/dsh-fs-local': 0.1.2-rc.1
  '@deepseek-ai/dsh-fs-observation-policy': 0.1.2-rc.1
  '@deepseek-ai/dsh-fs-sandbox': 0.1.2-rc.1
  '@deepseek-ai/dsh-llm': 0.1.2-rc.1
  '@deepseek-ai/dsh-llm-replay': 0.1.2-rc.1
  '@deepseek-ai/dsh-sandbox': 0.1.2-rc.1
  '@deepseek-ai/dsh-sandbox-policy': 0.1.2-rc.1
  '@deepseek-ai/dsh-session': 0.1.2-rc.1
  '@deepseek-ai/dsh-session-projection': 0.1.2-rc.1
  '@deepseek-ai/dsh-storage': 0.1.2-rc.1
  '@deepseek-ai/dsh-storage-domain': 0.1.2-rc.1
  '@deepseek-ai/dsh-storage-json': 0.1.2-rc.1
  '@deepseek-ai/dsh-system-prompt': 0.1.2-rc.1
  '@deepseek-ai/dsh-tool-fs': 0.1.2-rc.1
  '@deepseek-ai/dsh-tool-str-replace-editor': 0.1.2-rc.1
  '@deepseek-ai/dsh-tools': 0.1.2-rc.1
  zod: 4.4.3
